In [90]:
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 
import pandas as pd
import numpy as np


# Training a Decision tree classifier on the oxo-game.csv dataset generated by the mcts code and storing the classifier in a pickle file dt1.pickle

In [155]:
dt10=pd.read_csv("data_9.csv",header=None)

In [157]:
dt10.head()

0   1   2   3   4   5   6   7   8   9   10
0   2   0   0   0   0   0   0   0   0   0   0
1   1   1   0   0   0   0   0   0   0   0   4
2   2   1   0   0   0   2   0   0   0   0   1
3   1   1   1   0   0   2   0   0   0   0   2
4   2   1   1   2   0   2   0   0   0   0   6

In [158]:
dt10.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [159]:
x=dt10.iloc[:,1:10]
y=dt10.iloc[:,10]

In [160]:
x.head(),y.head()

(   1  2  3  4  5  6  7  8  9
 0  0  0  0  0  0  0  0  0  0
 1  1  0  0  0  0  0  0  0  0
 2  1  0  0  0  2  0  0  0  0
 3  1  1  0  0  2  0  0  0  0
 4  1  1  2  0  2  0  0  0  0, 0    0
 1    4
 2    1
 3    2
 4    6
 Name: 10, dtype: int64)

In [161]:
X_train,X_test,Y_train,Y_test=train_test_split(x, y, test_size=0.20,random_state=20,stratify=y)

In [162]:
parameters_dt = {'criterion':('gini', 'entropy'),
'max_depth':range(2, 10),
'class_weight':('balanced', None),
'presort':(False,True),
}

dt = DecisionTreeClassifier()
clf_dt = GridSearchCV(dt, parameters_dt,cv = 5, scoring = 'accuracy')
clf_dt1=clf_dt.fit(X_train, Y_train)
def display(results):
    print(f'the best results are :{results.best_params_}')
display(clf_dt)
dt_pred=clf_dt1.predict(X_test)
accuracy_score(Y_test,dt_pred)

the best results are :{'class_weight': 'balanced', 'criterion': 'entropy', 'max_depth': 9, 'presort': False}


C:\Users\Dilba\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


0.7630057803468208

In [163]:
tree = DecisionTreeClassifier(class_weight='balanced',criterion='entropy',max_depth=9,presort= False)
clf_dt=tree.fit(X_train, Y_train)
dt_pred = clf_dt.predict(X_test)
dt_pred
accuracy_dt=round(accuracy_score(Y_test, dt_pred)*100,2)
print("Accuracy with Pruned Decision Tree Classifier :"+ str(accuracy_dt)+" %")
kappa_stats=round(metrics.cohen_kappa_score(dt_pred,Y_test),2)
print(kappa_stats)

Accuracy with Pruned Decision Tree Classifier :76.3 %
0.73


In [164]:
import pickle
pickle_out = open("dt10.pickle","wb")
pickle.dump(clf_dt, pickle_out)
pickle_out.close()

In [165]:
with open('dt-classifier.csv','a+') as f1:
    f1.write('dt10.pickle' +',')
    f1.write(str(accuracy_dt)+',')
    f1.write(str(kappa_stats))
    f1.write('\n')
f1.close 

<function TextIOWrapper.close()>

In [166]:
results=confusion_matrix(Y_test, dt_pred)
print('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(Y_test, dt_pred))
print('Report : ')
print(classification_report(Y_test, dt_pred))

Confusion Matrix :
[[15  0  3  0  1  0  0  0  1]
 [ 1 16  2  0  0  1  0  0  0]
 [ 0  0 19  0  0  0  0  0  0]
 [ 0  0  4 10  0  2  2  2  0]
 [ 0  0  8  0 12  0  0  0  0]
 [ 0  0  0  1  0 11  0  1  5]
 [ 0  0  3  0  0  2 13  0  0]
 [ 0  1  0  0  0  0  0 17  0]
 [ 0  0  0  0  0  1  0  0 19]]
Accuracy Score : 0.7630057803468208
Report : 
              precision    recall  f1-score   support

           0       0.94      0.75      0.83        20
           1       0.94      0.80      0.86        20
           2       0.49      1.00      0.66        19
           3       0.91      0.50      0.65        20
           4       0.92      0.60      0.73        20
           5       0.65      0.61      0.63        18
           6       0.87      0.72      0.79        18
           7       0.85      0.94      0.89        18
           8       0.76      0.95      0.84        20

    accuracy                           0.76       173
   macro avg       0.81      0.76      0.76       173
weighted avg  